### ISSUE TITLE
Let's make this a package

### ISSUE THREAD

**Issue by hwayne** [hwayne/tlacli#3]
So that people don't have to navigate to the folder every dang time

**Comment by danielcompton** [comment]
Not sure how hard it would be, but it would be handy to have a Homebrew package based on the Python package. This would be even more 'safe' for me to install. Then I don't need to worry about which Python I'm using, or conflicting packages, or any of the other issues with installing Python packages to the system Python.

**Comment by ajdavis** [comment]
I can help making this a PyPI package.

**Comment by hwayne** [comment]
So uh, I was trying to fix the tests and I accidentally write a `setup.py` file

I guess the good news is this is going to be on PyPI a lot sooner than I expected

**Comment by Kavec** [comment]
https://github.com/python-poetry/poetry might be worth looking in to, as well. 

Upside:

- Ejects/hides a lot of the historical cruft of setup.py/requirement*.txt/virtualenvs/&c in favor of [PEP 518 pyproject.toml](https://www.python.org/dev/peps/pep-0518/)

- Does the upload-to-pypi step out of the box

Downside:

- Relies on something like pyenv or tox to actually manage the installed python versions 

—

I’m a big fan of this either way— most of my TLA+ stuff is done via the vscode extension. Being able to tell team members to install a package to interact with specs from the command line is much more feasible than asking them to configure a UI that I don’t spend time with myself.

**Comment by hwayne** [comment]
Oops broke the package

**Comment by hwayne** [comment]
Fixed I think???

**Comment by hwayne** [comment]
This is NOT gonna look good in the Thought Leader Annual Reviews

**Comment by hwayne** [comment]
WE DID IT https://pypi.org/project/tlacli/0.0.1/

**Comment by ajdavis** [comment]
Marvelous!
